# Generated by Django 2.2 on 2020-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryicon',
            name='ci_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='中文名称'),
        ),
    ]
